---
name: CD - Deployment

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      env:
        description: "Target env"
        required: true
        type: string
      image-tag:
        description: "Container image tag to deploy"
        required: false
        type: string
        default: "latest"
    secrets:
      TS_OAUTH_CLIENT_ID:
        required: true
      TS_OAUTH_CLIENT_SECRET:
        required: true
      DEPLOY_HOST:
        required: true
      DEPLOY_USER:
        required: true
      DEPLOY_SSH_KEY:
        required: true
      CF_TUNNEL_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      env:
        description: "Target env"
        required: true
        type: choice
        options:
          - dev
          - prod
        default: "dev"
      image-tag:
        description: "Container image tag to deploy"
        required: false
        default: "latest"

concurrency:
  group: cd-${{ inputs.env }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

permissions:
  contents: read
  security-events: write

jobs:

  sbom_scan:
    name: SBOM Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:

      - name: Generate SBOM with Syft
        id: container
        uses: anchore/sbom-action@61119d458adab75f756bc0b9e4bde25725f86a7a # v0.17.2
        with:
          image: "ghcr.io/${{ github.repository }}:${{ inputs.image-tag }}"
          format: 'spdx-json'
          output-file: 'sbom.spdx.json'

      - name: Scan SBOM with Grype
        id: sbom
        uses: anchore/scan-action@64a33b277ea7a1215a3c142735a1091341939ff5 # v4.1.2
        with:
          sbom: 'sbom.spdx.json'
          fail-build: false
          severity-cutoff: 'high'

      - name: Upload Grype scan results
        uses: github/codeql-action/upload-sarif@4f3212b61783c3c68e8309a0f18a699764811cda # v3.27.1
        if: always()
        with:
          sarif_file: ${{ steps.sbom.outputs.sarif }}

      - name: Check status of potentially failing step and issue warning
        if: steps.sbom.outcome == 'failure'
        run: |
          echo "::error::The previous step detected potential vulnerabilities in the associated SBOM. Please review the report above."
          exit 1
        shell: bash

  deploy:
    needs:
      - sbom_scan
    name: Deploy to ${{ inputs.env }}
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    environment:
      name: ${{ inputs.env }}
      url: ${{ vars.ENVIRONMENT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Connect to Tailnet
        uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4a # v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          ping: ${{ secrets.DEPLOY_HOST }}
          tags: tag:ci

      - name: Update image tag in compose.yml
        if: inputs.env == 'dev'
        run: |
          sed -i 's|ghcr.io/mighty-muffin/ibc:latest|ghcr.io/mighty-muffin/ibc:gha-${{ github.run_id }}|g' compose.yml
        shell: bash

      - name: Docker Compose Upload and Deploy
        uses: cssnr/stack-deploy-action@1c955fe3e2d56cfd5fde6102374beb16b0c0ce41 # v1.5.0
        env:
          CF_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
        with:
          name: "ibc-${{ inputs.env }}"
          file: "compose.yml"
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
          mode: compose
