---
name: CI - SBOM with Dependency-Track

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - demo/*
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  docker_build:
    name: Container Build
    runs-on: ubuntu-24.04
    outputs:
      image-tag: ${{ steps.image-tag.outputs.image-tag }}
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=raw,value=latest,enable={{is_default_branch}},priority=100
            type=ref,event=branch,priority=100
            type=raw,value=gha-${{ github.run_id }},enable=${{github.event_name == 'pull_request'}},priority=200
            type=raw,value=nightly-${{ github.run_id }},enable=${{github.event_name == 'schedule'}},priority=200
            type=ref,event=pr,priority=200
            type=ref,event=tag,priority=200
            type=sha,value={{sha}},enable={{is_default_branch}},priority=300

      - name: Docker Build
        id: build_image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          platforms: |
            linux/amd64
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            GIT_COMMIT=${{ github.sha }}
            REPO_URL=${{ github.server_url }}/${{ github.repository }}

      - name: Find the primary image tag we just pushed, and output it
        id: image-tag
        run: |
          # shellcheck disable=SC2086
          echo "image-tag=${{ steps.docker_meta.outputs.version }}" >> $GITHUB_OUTPUT
        shell: bash

  sbom:
    name: Generate & Push SBOM to Dependency-Track
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - "3.10.11-alpine3.16"
          - "3.10.11-alpine3.17"
          - "3.10.11-alpine3.18"
    timeout-minutes: 5

    steps:
      - name: Connect to Tailnet # VPN connection to access Dependency-Track server
        uses: tailscale/github-action@53acf823325fe9ca47f4cdaa951f90b4b0de5bb9 # v4.1.1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          ping: ${{ secrets.DEPLOY_HOST }}
          tags: "tag:ci"

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@28d71544de8eaf1b958d335707167c5f783590ad # v0.22.2
        with:
          image: ghcr.io/${{ github.repository }}:${{ needs.docker_build.outputs.image-tag }}
          format: cyclonedx-json
          artifact-name: ${{ github.run_id }}-sbom.json
          output-file: ${{ github.workspace }}/${{ github.run_id }}-sbom.json

      - name: Upload SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5 # v3.1.0
        with:
          serverhostname: ${{ secrets.DEPENDENCYTRACK_HOST_URL }}
          apikey: ${{ secrets.DEPENDENCYTRACK_TOKEN }}
          projectname: "A-demo-test-project"
          projectversion: "0.0.1"
          bomfilename: ${{ github.workspace }}/${{ github.run_id }}-sbom.json
          autocreate: true
